version: "3"
services:
  postgres:
    container_name: node-server_postgres
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - ./data/postgres:/data/postgres
    env_file:
    - ./.env